batch_size: 64
num_devices: 4
momentum_base: 0.996
momentum_max: 1.0
momentum_increase: true
dataset: imagenet50_train_val
eval_metric:
  - nmi
  - acc
  - ari
whole_dataset: false
encoder_name: resnet50
epochs: 300
feat_dim: 256
hidden_size: 4096
img_size: 224
lambda_predictor_lr: 10
learning_rate: 0.05
learning_eta_min: 0.
reassign: 1
save_freq: 1
save_checkpoints: false
shuffling_bn: true
symmetric: true
temperature: 0.5
use_gaussian_blur: true
warmup_epochs: 50
weight_decay: 0.0005
dist: true
data_resample: true
v2: true
test_resized_crop: true

model_name: propos
cluster_loss_weight: 0.1
latent_std: 0.001

wandb: false
project_name: 'clustering_archives'
entity: 'zzhuang'

data_folder: '/home/exx/Documents/Datasets/'
models_dir: '/home/exx/Documents/AutoProPos/models_save_dir/'
resume_name : 'imagenet50'

clusternet: true
epochs_cluster_analysis: [50,100,200]
num_cluster: 200
channels: 3

resize: None

save_checkpoints: false
save_best_model: false
load_best_model: true
resume_name: 'imagenet50'

clusternet_training_data: 24000
autoencoder_latent_dim: 5
cluster_range: [20,70]
n_candidate_autoencoder_clustering: 15
autoencoder_training_epoch: 120
n_candidate_k_mean: 5
n_candidate_k_max: 5

