batch_size: 64
num_devices: 4
momentum_base: 0.996
momentum_max: 1.0
momentum_increase: true
dataset: cifar20
eval_metric:
  - nmi
  - acc
  - ari
whole_dataset: true
encoder_name: bigresnet34
epochs: 1000
feat_dim: 256
hidden_size: 4096
img_size: 32
lambda_predictor_lr: 10
learning_rate: 0.05
learning_eta_min: 0.
reassign: 1
save_freq: 1
save_checkpoints: false
shuffling_bn: true
symmetric: true
temperature: 0.5
use_gaussian_blur: false
warmup_epochs: 50
weight_decay: 0.0005
dist: true
data_resample: true
v2: true
use_copy: true

model_name: propos_cifar20_r34
cluster_loss_weight: 0.1
latent_std: 0.001

wandb: false
project_name: 'clustering_archives'
entity: 'zzhuang'

data_folder: '/home/exx/Documents/Cyril_Kana_Python_Project/Projjet_cours_profond/'
models_dir: '/home/exx/Documents/AutoProPos/Models/'

save_checkpoints: false
save_best_model: true
load_best_model: false

resume_epoch: 0
test_freq: 50

clusternet: true
epochs_cluster_analysis: [300,500,700]
num_cluster: 200
channels: 3

resize: None

clusternet_training_data: 24000
cluster_range: [2,40]
autoencoder_latent_dim: 4
n_candidate_autoencoder_clustering: 15
autoencoder_training_epoch: 120
n_candidate_k_mean: 5 
n_candidate_k_max: 5
