batch_size: 64
num_devices: 4
momentum_base: 0.996
momentum_increase: false
dataset: stl10
eval_metric:
  - nmi
  - acc
  - ari
whole_dataset: false
encoder_name: resnet34
epochs: 1000
feat_dim: 256
hidden_size: 4096
img_size: 224
lambda_predictor_lr: 10
learning_rate: 0.05
learning_eta_min: 0.
reassign: 1
save_freq: 1
save_checkpoints: false
shuffling_bn: true
symmetric: true
temperature: 0.5
use_gaussian_blur: false
warmup_epochs: 50
weight_decay: 0.0005
dist: true

model_name: propos_stl
cluster_loss_weight: 0.1
latent_std: 0.001

wandb: false
project_name: 'Clustering'
entity: 'Hzzone'

save_checkpoints: false
save_best_model: true
load_best_model: false

data_folder: '/home/exx/Documents/Cyril_Kana_Python_Project/ProposDPM_v2/src/ProPos/datasets'
models_dir: '/home/exx/Documents/AutoProPos/Models/'
resume_epoch: 0
test_freq: 50

v2: false

clusternet: true
epochs_cluster_analysis: [200,400,600]
num_cluster: 200
channels: 3

resize: None

clusternet_training_data: 5000
cluster_range: [2,30]
autoencoder_latent_dim: 5
n_candidate_autoencoder_clustering: 4
autoencoder_training_epoch: 120
n_candidate_k_mean: 5 
n_candidate_k_max: 5
