batch_size: 312
num_devices: 4
momentum_base: 0.996
momentum_increase: false
dataset: fashionmnist
eval_metric:
  - nmi
  - acc
  - ari
whole_dataset: false
encoder_name: lightresnet18_grayscale
epochs: 500
feat_dim: 128
hidden_size: 4096
img_size: 28
lambda_predictor_lr: 10
learning_rate: 0.05
learning_eta_min: 0.
reassign: 1
save_freq: 1
save_checkpoints: false
shuffling_bn: true
symmetric: true
temperature: 0.5
use_gaussian_blur: false
warmup_epochs: 100
weight_decay: 0.0005
dist: true

model_name: propos
cluster_loss_weight: 0.1
latent_std: 0.001

wandb: false
project_name: 'Clustering'
entity: 'user'


data_folder: '/home/exx/Documents/AutoProPos/Datasets/'
models_dir: '/home/exx/Documents/AutoProPos/models_save_dir/'

save_checkpoints: false
save_best_model: true
load_best_model: false

resume_epoch: 0
test_freq: 50

to_rgb: false
resize: None
channels: 1

custom_normalize_params: 
  - [0.5]
  - [0.5]

permute: true
clusternet: true
epochs_cluster_analysis: [100,200,400]
num_cluster: 200
clusternet_training_data: 24000
cluster_range: [2,30]
n_candidate_autoencoder_clustering: 4
autoencoder_training_epoch: 120
n_candidate_k_mean: 5 
n_candidate_k_max: 10
