batch_size: 256 
num_devices: 4 
momentum_base: 0.996
momentum_increase: false
dataset: mnist
eval_metric:
  - nmi
  - acc
  - ari
whole_dataset: false 
encoder_name: lightresnet18_grayscale
epochs: 2
feat_dim: 256
hidden_size: 4096
img_size: 28
lambda_predictor_lr: 10
learning_rate: 0.05
learning_eta_min: 0.
reassign: 1
save_freq: 1
save_checkpoints: false
shuffling_bn: true
symmetric: true
temperature: 0.5
use_gaussian_blur: false
warmup_epochs: 50
weight_decay: 0.0005
dist: true
model_name: propos
cluster_loss_weight: 0.1
latent_std: 0.001
wandb: false
project_name: 'Clustering'
entity: 'user'
data_folder: '/home/exx/Documents/AutoProPos/Datasets/'
models_dir: '/home/exx/Documents/AutoProPos/models_save_dir/'
save_checkpoints: false
save_best_model: true
load_best_model: false
resume_epoch: 0
test_freq: 50
to_rgb: false
resize: None
channels: 1
custom_normalize_params: 
  - [0.1307]
  - [0.3081]
clusternet: true
epochs_cluster_analysis: [200,400,600,800]
num_cluster: 200
channels: 1
resize: None
clusternet_training_data: 24000
cluster_range: [2,30]
n_candidate_autoencoder_clustering: 4
autoencoder_training_epoch: 70
n_candidate_k_mean: 5 
n_candidate_k_max: 5

