batch_size: 64
num_devices: 4
momentum_base: 0.996
momentum_max: 1.0
momentum_increase: true
dataset: imagenetdogs
eval_metric:
  - nmi
  - acc
  - ari
whole_dataset: true
encoder_name: resnet34
epochs: 1000
feat_dim: 256
hidden_size: 4096
#img_size: 96
img_size: 224
lambda_predictor_lr: 10
learning_rate: 0.05
learning_eta_min: 0.
reassign: 1
save_freq: 1
save_checkpoints: false
shuffling_bn: true
symmetric: true
temperature: 0.5
#use_gaussian_blur: false
use_gaussian_blur: true
warmup_epochs: 50
weight_decay: 0.0005
dist: true
data_resample: true
v2: true
#byol_transform: true
test_resized_crop: true

model_name: propos
cluster_loss_weight: 0.1
latent_std: 0.001

wandb: false
project_name: 'clustering_archives'
entity: 'user'


data_folder: '/home/exx/Documents/AutoProPos/Datasets'
models_dir: '/home/exx/Documents/AutoProPos/models_save_dir/'

save_checkpoints : false

save_best_model : false

load_best_model : true
resume_name : 'imagenetdogs'

clusternet: true 
epochs_cluster_analysis : [200,400,600,800]  
num_cluster : 200
channels: 3

resize: None

clusternet_training_data: 19500 
autoencoder_latent_dim: 5
cluster_range: [2,30]
n_candidate_autoencoder_clustering : 4
autoencoder_training_epoch : 120 
n_candidate_k_mean : 5 
n_candidate_k_max : 5
